<?php
/*
 * Copyright (C) 2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/*
 * Created: 2018-01-28 00:07:45
 * File:    about.phtml
 * 
 * Author:  Anders Lövgren (Nowise Systems)
 */

?>

<div class="tabs">
    <ul>
        <li><a href="#tabs-0"><?= $tr->_("General") ?></a></li>
        <li><a href="#tabs-1"><?= $tr->_("Authors") ?></a></li>
        <li><a href="#tabs-2"><?= $tr->_("Contributors") ?></a></li>
        <li><a href="#tabs-3"><?= $tr->_("License") ?></a></li>
        <li><a href="#tabs-4"><?= $tr->_("Project") ?></a></li>
    </ul>

    <div id="tabs-0">
        <p>
            <?= $composer->description ?>
        </p>
        <p>
            <?= $tr->_("OpenExam Online v%version%", array('version' => $composer->version)) ?>
        </p>
    </div>

    <div id="tabs-1">
        <?php foreach ($composer->authors as $author): ?>
                <p>
                    <button class="btn btn-success about-link-mail" style="min-width: 165px; text-align: left" data-link="<?= $author->email ?>">
                        <i class="fa fa-user"></i> 
                        <?= $author->name ?>
                    </button> - 
                    <a href="<?= $author->homepage ?>"><?= $author->homepage ?></a> (<?= $author->role ?>) 
                </p>
        <?php endforeach; ?>
    </div>

    <div id="tabs-2">
        <p>
            <?= $tr->_("The following organizations has contributed to the project:") ?>
        </p>
        <?php foreach ($composer->contributors as $contributor): ?>
                <p>
                    <button class="btn btn-success about-link-href" style="min-width: 165px; text-align: left" data-link="<?= $contributor->link ?>">
                        <i class="fa fa-sitemap"></i> 
                        <?= $contributor->name ?>
                    </button>
                </p>
        <?php endforeach; ?>
    </div>

    <div id="tabs-3">
        <p>
            <?= $tr->_("Released under %license% license.", array('license' => $composer->license)) ?>
        </p>
        <button class="btn btn-default" id="project-license-btn">
            <?= $tr->_("Details") ?>
        </button>
    </div>

    <div id="tabs-4">
        <p>
            <?= $tr->_("More information is available on the <a href=\"%homepage%\">project homepage</a>.", array('homepage' => $composer->homepage)) ?>
            <?= $tr->_("Source code can be downloaded from <a href=\"%projpage%\">GitHub</a>.", array('projpage' => $composer->projpage)) ?>
        </p>
        <p>
            <a href="<?= $composer->homepage ?>"><?= $composer->homepage ?></a><br>
            <a href="<?= $composer->projpage ?>"><?= $composer->projpage ?></a>
        </p>
    </div>

</div>

<div class="oe-dialog-buttons">
    <hr>
    <center>
        <span style="min-width: 10em" class="btn btn-success" id="about-close">
            <i class="fa fa-close"></i>
            <span>
                <?= $tr->_("Close") ?>
            </span>
        </span>
    </center>		
</div>   

<script>
        // 
        // Select first tab:
        // 
        $(".tabs").tabs({
            active: 0
        });

        // 
        // Load project license file into new dialog:
        // 
        $(document).on('click', '#project-license-btn', function () {
            $.ajax({
                type: "POST",
                url: baseURL + 'help/license',
                success: function (content) {
                    showDialogWindow("#project-license", content);
                },
                error: function (error) {
                    showDialogWindow("#project-license", error.responseText);
                }
            });
        });

        $(document).on('click', 'button.about-link-mail', function () {
            window.location.href = 'mailto:' + $(this).attr('data-link');
        });

        $(document).on('click', 'button.about-link-href', function () {
            window.location.href = $(this).attr('data-link');
        });
</script>

<div id="project-license" style="display: none" title="<?= $tr->_("Project license") ?>"></div>
