<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// Created: 2015-11-23 23:02:02
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<h1 class="success">
    <?= $tr->_("Help sections") ?>
</h1>
<div class="row">
    <?php foreach ($help as $section => $ds) : ?>
            <div class="col-lg-3 col-md-3 col-sm-3">
                <a href="<?= sprintf("%s/%s", $base, $section) ?>" 
                   title="<?= $tr->_("Click to display more manuals in various formats and translations") ?>">
                    <h2><?= $ds['name'] ?></h2>
                    <img src="<?= $icon ?>" style="padding-bottom:15px">
                </a>
                <ul>
                    <?php foreach ($ds['data'] as $target => $dt) : ?>
                            <li>
                                <a href="<?= sprintf("%s/%s/%s", $base, $section, $target) ?>">
                                    <?= $dt['name'] ?>
                                </a>
                            </li>
                    <?php endforeach; ?>
                    <br>
                    <li>
                        <a href="<?= sprintf("%s/%s", $base, $section) ?>">
                            <?= $tr->_("Other formats and translations...") ?>
                        </a>
                    </li>
                </ul>
            </div>
    <?php endforeach; ?>
</div>
<br><hr/>    
<p>
    <?= $tr->_("If you see this page, then you might have ended up on this page by misstake.") ?>
    <?= $tr->_("Please follow one of the links above to access desired content.") ?>
</p>
