<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// Created: 2015-11-23 23:02:33
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<h1 class="success">
    <?= $tr->_('Manuals') ?>
</h1>
<div class="row">
    <?php foreach ($manual as $section => $data) : ?>
            <div class="col-md-6 col-sm-6">
                <a href="<?= sprintf("%s/manual/%s", $base, $section) ?>">
                    <h2><?= $data['name'] ?></h2>
                    <img src="<?= $icon ?>" style="padding-bottom:15px" />
                </a>
                <ul>
                    <?php foreach ($data['data'] as $format => $name) : ?>
                            <li>
                                <a href="<?= sprintf("%s/manual/%s/%s/%s", $base, $section, $data['lang'][0], $format) ?>">
                                    <?= $name ?>
                                </a>
                                <?php if (count($data['lang']) > 1) : ?>
                                        <?php $links = array(); ?>
                                        <?php foreach ($data['lang'] as $language) : ?>
                                                <?php $links[] = sprintf("<a href=\"%s/manual/%s/%s/%s\">%s</a>", $base, $section, $language, $format, ucfirst($language)); ?>
                                        <?php endforeach; ?>
                                        <br/>[<?= implode(", ", $links) ?>]
                                <?php endif; ?>
                            </li>
                            <br>
                    <?php endforeach; ?>
                </ul>
            </div>
    <?php endforeach; ?>
</div>
<br><hr/>    
<p>
    <?= $tr->_("If you see this page, then you might have ended up on this page by misstake.") ?>
    <?= $tr->_("Please follow one of the links above to access desired content.") ?>
</p>
