<?php
/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    students.phtml
// Created: 2016-04-14 12:24:39
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<style>
    table, tr { 
        border: 1px solid black;
        margin: 0px;
        font-size: 0.9em;
        width: 22cm;
    }
    td {
        white-space: nowrap;
    }
    th {
        border-top: 1px solid black;
        border-bottom: 1px solid black;
        text-align: left;
        min-width: 30px;
    }
    tr.student:nth-child(odd) {
        background: #eeeeee;
    }
    th.notes {
        min-width: 400px;
    }
    .subject {
        text-decoration: underline
    }
    td.description {
        background-color: #eeeeee;
        padding: 10px;
        white-space: normal;
    }
</style>

<table>
    <tr>
        <td colspan="7">
            <b><?= $exam->name ?> (<?= $exam->code ?>)</b><br/>
            <span class="subject">
                <?= $tr->_("Department:") ?>
            </span> <?= $exam->orgunit ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <span class="subject">
                <?= $tr->_("Start:") ?>
            </span> <?= $exam->starttime ?>
        </td>
        <td colspan="2">
            <span class="subject">
                <?= $tr->_("End:") ?>
            </span> <?= $exam->endtime ?>
        </td>
    </tr>
    <tr><td></td></tr>
    <tr>
        <td colspan="7" class="description"><?= $exam->descr ?></td>
    </tr>
    <tr><td></td></tr>
    <tr>
        <td colspan="7">
            <span class="subject">
                <?= $tr->_("Contact:") ?>
            </span> <?= $contact->name ?> (<?= implode(", ", $contact->mail) ?>)
        </td>
    </tr>
    <tr><td><br/></td></tr>
    <tr>
        <th>
            <?= $tr->_("Name") ?>
        </th>
        <th>
            <?= $tr->_("Pers Nr") ?>
        </th>
        <th>
            <?= $tr->_("Code") ?>
        </th>
        <th>
            <?= $tr->_("User") ?>
        </th>
        <th>
            <?= $tr->_("Tag") ?>
        </th>
        <th>
            <?= $tr->_("ID") ?>
        </th>
        <th>
            <?= $tr->_("Finished") ?>
        </th>
        <th class="notes">
            <?= $tr->_("Notes") ?>
        </th>
    </tr>
    <?php foreach ($students as $student) { ?>
            <tr class="student">
                <td><?= $student->lname ?>, <?= $student->fname ?></td>
                <td><?= $student->persnr ?></td>
                <td><?= $student->code ?></td>
                <td><?= $student->user ?></td>
                <td><?= $student->tag ?></td>
                <td></td>
                <td><?= $student->finished ?></td>
                <td><br><br></td>
            </tr>
    <?php } ?>
</table>
