<?php

use Phalcon\Tag;

/*
 * Copyright (C) 2014-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// 
// Author:  Ahsan Shahzad (Medfarm DoIT)
//          Anders Lövgren (Nowise Systems)
// 

?>

<style>
    .task-button-group {
        margin-top: 25px;
        margin-bottom: 25px;
    }
    .task-button {
        margin: 5px;
        padding-top: 20px;
        min-height: 120px; 
        min-width: 160px;
        text-align:center;
        line-height:40px;
    }
    .task-button a {
        color: white;
        min-height: 120px;
        display: inline-table;
        background: red;
    }
</style>

<div class="jumbotron box-shadow" style="padding:20px">
    <h1 class="main"><?= $tr->_("Welcome!") ?></h1>
    <br />
    <div>
        <?= $tr->_("OpenExam is an on line examination system that allows different types of computer-based tests and exams.") ?>
        <?= $tr->_("It replaces traditional paper-based exams if performed in exam halls equipped with computers or in computer class rooms where restricted interned can be controlled.") ?>
        <?= $tr->_("It may also be used for home exams and diagnostic tests on student’s personal devices.") ?>
        <?= $tr->_("The front end of the system is entirely web based, from creating the exam to providing the students with the corrected exams.") ?>
    </div>

    <div class="task-button-group">
        <?php if ($this->user->roles->hasRole('teacher')) : ?>
                <a href="<?= $this->url->get('exam/create') ?>">
                    <span class="btn btn-success task-button">
                        <i class="fa fa-plus-circle fa-2x"></i><br>
                        <?= $tr->_('Create Exam...') ?>
                    </span>
                </a>
        <?php endif; ?>
        <?php if ($this->user->roles->hasRole('contributor')) : ?>
                <a href="<?= $this->url->get('task/contribute') ?>">
                    <span class="btn btn-success task-button">
                        <i class="fa fa-share-alt-square fa-2x"></i><br>
                        <?= $tr->_('Contribute Questions') ?>
                    </span>
                </a>
        <?php endif; ?>
        <?php if ($this->user->roles->hasRole('corrector')) : ?>
                <a href="<?= $this->url->get('task/correct') ?>">
                    <span class="btn btn-success task-button">
                        <i class="fa fa-save fa-2x"></i><br>
                        <?= $tr->_('Correct Answers') ?>
                    </span>
                </a>
        <?php endif; ?>
        <?php if ($this->user->roles->hasRole('invigilator')) : ?>
                <a href="<?= $this->url->get('task/invigilate') ?>">
                    <span class="btn btn-success task-button">
                        <i class="fa fa-paperclip fa-2x"></i><br>
                        <?= $tr->_('Invigilate Exam') ?>
                    </span>
                </a>
        <?php endif; ?>
        <?php if ($this->user->roles->hasRole('decoder')) : ?>
                <a href="<?= $this->url->get('task/decode') ?>">
                    <span class="btn btn-success task-button">
                        <i class="fa fa-flag fa-2x"></i><br>
                        <?= $tr->_('Decode Exam') ?>
                    </span>
                </a>
        <?php endif; ?>
        <?php if ($this->user->roles->hasRole('student')) : ?>
                <a href="<?= $this->url->get('task/result') ?>">
                    <span class="btn btn-success task-button">
                        <i class="fa fa-list-alt fa-2x"></i><br>
                        <?= $tr->_('Download Results') ?>
                    </span>
                </a>
        <?php endif; ?>
    </div>

    <div style="padding-bottom:10px">
        <?= $tr->_("Through the links below, teachers and course providers can log in and create an exam, assign different roles to teachers contributing to the exam.") ?>
        <?= $tr->_("Students can also log in and get access to their completed exams and find information about upcoming exams.") ?>
        <?= Tag::linkTo('help/manual', $tr->_('Read more..')) ?>
    </div>
</div>

<div class="row" style="padding:10px">
    <div class="col-lg-4 col-md-4 col-sm-4">
        <h2>
            <?= $tr->_("Are you a Teacher?") ?>
        </h2>
        <div>
            <img src="<?= $this->url->get("img/teachers.jpg") ?>" style="padding-bottom:15px;" />
            <p>
                <?= $tr->_("If you are a teacher or if you have been given access to the system by the administrator you can log in by clicking on \"Login\" link in top right corner.") ?>
            </p>
            <p>
                <?=
                $tr->_("If you do not have access, please contact <a href=\"mailto:%addr%\">%name%</a>.", array(
                        'addr' => $this->config->contact->addr,
                        'name' => $this->config->contact->name))

                ?>
            </p>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4" style="background-color: #f0f0f0">
        <h2>
            <?= $tr->_("Are you a Student?") ?>
        </h2>
        <div>
            <img src="<?= $this->url->get("img/students.jpg") ?>" style="padding-bottom:15px" />
            <p>
                <?= $tr->_("If you have been registered for computer based exams you can log in by clicking on \"Login\" link in top right corner and find your previous and upcoming exams.") ?>
                <?= $tr->_("If you cannot log in please contact your course administrator.") ?>
            </p>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
        <h2>
            <?= $tr->_("Getting started") ?>
        </h2>
        <div>
            <img src="<?= $this->url->get("img/flight-sky-earth-space.jpeg") ?>" style="padding-bottom:15px;" />
            <p>
                <?= $tr->_("If this is your first use of the system, please take some time to read the student or teacher manual.") ?>
            </p>
            <p>
                <?= Tag::linkTo('help/manual', $tr->_('Read the manuals')) ?>
            </p>
        </div>
    </div>
</div>
