<?php
/*
 * Copyright (C) 2016-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    show500.phtml
// Created: 2016-12-12 00:12:27
// 
// Author:  Anders Lövgren (Nowise Systems)
// 

?>

<?php $this->partial("error/partial/style"); ?>
<?php $this->partial("error/partial/script"); ?>

<h1 class="header">
    <i class="fa fa-exclamation-circle" aria-hidden="true" style="color: red"></i>
    <?= $tr->_("Internal system error:") ?>
</h1>

<p class="message">
    <?= $error->getMessage(); ?>
</p>

<div class="info">
    <p>
        <?= $tr->_("There was an error processing the request.") ?>
        <?= $tr->_("It might be caused by a miss configuration or an external service no longer working.") ?>
    </p>
    <p>
        <?= $tr->_("This kind of error is usually permanent and will persist until been taking cared of by someone.") ?>
        <?= $tr->_("Please click on the <u>report button</u> to send an email to the system manager.") ?>
        <?= $tr->_("In case of <u>emergency</u>, please call %phone% immediately", array('phone' => $contact['phone'])) ?>           
    </p>
    <button class="btn btn-warning" value="report" onclick="return report_exception()">
        <?= $tr->_("Report") ?>
    </button>
    <span id="notice" style="display: block"></span>
</div>
