<?php

use Phalcon\Tag;

/*
 * Copyright (C) 2014-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    view.phtml
// 
// Author:  Ahsan Shahzad (MedfarmDoIT)
// Author:  Anders Lövgren (Nowise Systems)
// 

?>

<!-- TODO: Load only if a question type is canvas -->
<?= Tag::stylesheetLink("plugins/canvas/css/literallycanvas.css?ver=0.4.14"); ?>
<?= Tag::stylesheetLink("plugins/ckeditor/skins/notification.css?ver=4"); ?>
<?= Tag::javascriptInclude('plugins/canvas/js/react-with-addons.js?ver=0.4.14'); ?>
<?= Tag::javascriptInclude('plugins/canvas/js/ie_customevent.js?ver=0.4.14'); ?>
<?= Tag::javascriptInclude('plugins/canvas/js/literallycanvas.min.js?ver=0.4.14'); ?>

<?= Tag::javascriptInclude('js/views/question/view.js?rev=2'); ?>

<style>
    .zoomWindow {
        box-shadow: 5px 5px 20px rgba(136,136,136,0.8);
        border-radius: 3px;
    }
    body.high-contrast .zoomWindow {
        filter: invert(100%);
    }

</style>

<div class='col-xs-12'>

    <!-- Question title row -->
    <?php if ($testMode): ?>
            <div class="alert alert-info clearfix" style="margin:15px 0px;">  
                <strong>
                    <?= $tr->_("Test mode activated.") ?>
                </strong> 
                <br/>
                <?= $tr->_("You are currently previewing the student view in test mode. Please note that answers will <strong>not</strong> be saved.") ?>
                <br/>
                <a href="<?= $this->url->get('exam/index') ?>" class="btn btn-primary pull-right">
                    <i class="icon-ok-circle"> 
                        <span>
                            <?= $tr->_("Finished") ?>
                        </span>
                    </i>
                </a>
            </div>
    <?php endif; ?>

    <?php if (!$testMode && $viewMode == 'all'): ?>
            <div class="alert alert-info alert-dismissable" style="margin:15px 0px;">  
                <a href="#" data-dismiss="alert" class="close">×</a>
                <p>
                    <strong>
                        <?= $tr->_("Careful preview all of your answers before quitting!") ?>
                    </strong>
                </p>
                <p>
                    <?= $tr->_("All answers seen below has been read directly from the database. If something is wrong, then contact the invigilator immediately.") ?>
                    <br>
                    <?= $tr->_("Please sign out and close all opened browser windows once you are satisfied with your answers.") ?>
                </p>
            </div>
    <?php endif; ?>

    <?php if (!$testMode && $viewMode == 'none') : ?>
            <div class="alert alert-warning" style="margin:15px 0px;">  
                <strong>
                    <?= $tr->_("Question is missing.") ?>
                </strong> 
                <br/>
                <?= $tr->_("This exam seems to have no questions. Please inform the invigilator about this problem to get it fixed.") ?>
            </div>
    <?php endif; ?>

    <?php
    // 
    // This is a mess: The $quest parameter is sometimes an object and sometimes an array depending 
    // on from where the view is used :-( (AL).
    // 
    $qSize = count($quest);
    $unanswered = 0;

    $prevQuestId = $nextQuestId = $currQuestId = false;
    $qNumber = 0;
    $qIndexes = array();

    // 
    // Set ID of previous and next question. Random access is only supported 
    // if result set is an array.
    // 
    if (count($quest) == 1) {
            foreach ($questions as $index => $question) {
                    $qIndexes[$index] = $question->id;
            }

            $target = current($quest);  // Get first from array

            foreach ($qIndexes as $index => $qIndex) {
                    if ($target->id == $qIndex) {
                            if (isset($qIndexes[$index - 1])) {
                                    $prevQuestId = $qIndexes[$index - 1];
                            }
                            if (isset($qIndexes[$index + 1])) {
                                    $nextQuestId = $qIndexes[$index + 1];
                            }

                            $currQuestId = $qIndex;

                            break;
                    }
            }
    }

    ?>

    <?php foreach ($quest as $qObj) : ?>
            <?php
            if (!$qObj->id) {
                    continue;
            }

            $qParts = json_decode($qObj->quest, true);
            $answerData = json_decode($answer[$qObj->id]->answer, true);

            ?>
            <!-- question content row -->
            <div class="row" style="margin-top:15px">

                <div class="col-sm-12">
                    <div class="box bordered-box blue-border">
                        <div class="box-content box-double-padding" style="font-family:verdana; <?= $viewMode == 'all' ? 'border-bottom: 10px solid #BE2435' : '' ?>">
                            <i class="q-no icon-q<?= $qObj->slot ?> text-contrast">:</i>
                            <?php $partCount = 1; ?>
                            <?php foreach ($qParts as $qPart => $qPartData): ?>

                                    <?php if (count($qParts) > 1): ?>
                                            <span class="q-part-title"><?= $qPart ?>.</span>                                        	
                                    <?php endif; ?>

                                    <?php if ($qPartData['q_points']) : ?>
                                            <span class="q-part-pts" style="font-weight:bold; <?= $qPart == 'a' ? 'border-radius: 0 0 5px' : '' ?>"><?= floatval($qPartData['q_points']) ?> pt.</span>
                                    <?php endif; ?>

                                    <div style="margin-bottom: 0;" class="form q-part" data-id="<?= $qPart ?>" >
                                        <fieldset>
                                            <div class="q-part-ans-area col-sm-7 col-sm-offset-1" <?= !count($qPartData['resources']) ? 'style="width:100%"' : '' ?>>
                                                <div class="q-part-text" style="padding-bottom:10px">
                                                    <div><?= $qPartData['q_text'] ?></div>
                                                </div>

                                                <?php if ($viewMode == 'all'): ?>

                                                        <?php if (is_array($qPartData['ans_area']['data']) && count($qPartData['ans_area']['data'])): ?>
                                                                <div>
                                                                    <ul>
                                                                        <?php foreach ($qPartData['ans_area']['data'] as $qPartOpt => $ans): ?>
                                                                                <li><?= $qPartOpt ?></li>
                                                                        <?php endforeach; ?>
                                                                    </ul>
                                                                </div>                                                                        
                                                        <?php endif; ?>

                                                        <?php if (!empty($answerData[$qPart]['ans'][0])): ?>
                                                                <div style="color:#0f74a8; padding-top:15px; padding-bottom: 5px">
                                                                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                                                    <?= $tr->_("Your Answer:") ?>
                                                                </div>
                                                                <div style="background-color:#F4F4F4; border-left: 5px solid #dedede; padding:10px">
                                                                    <?php if (count($answerData[$qPart]['ans']) > 1): ?>
                                                                            <ul>
                                                                                <?php foreach ($answerData[$qPart]['ans'] as $optAns): ?>
                                                                                        <li><?= $optAns ?></li>
                                                                                <?php endforeach; ?>
                                                                            </ul>
                                                                    <?php else: ?>
                                                                            <?php if ($answerData[$qPart]['type'] == 'canvas'): ?>
                                                                                    <img class="img-zoom-inner" src="<?= $answerData[$qPart]['ans'][0]['canvasUrl'] ?>" data-zoom-image="<?= $answerData[$qPart]['ans'][0]['canvasUrl'] ?>" style="max-width:100%; background-color:#f4f4f4" />
                                                                            <?php else: ?>
                                                                                    <?= $answerData[$qPart]['ans'][0] ?>
                                                                            <?php endif; ?>
                                                                    <?php endif; ?>
                                                                </div>
                                                        <?php else: ?>
                                                                <div style="color:#f45956; padding-top:15px; padding-bottom: 5px">
                                                                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                                                                    <?= $tr->_("Your Answer:") ?>
                                                                </div>
                                                                <div style="border-left: 5px solid #f45956; padding:10px">
                                                                    <i>
                                                                        <?= $tr->_("You haven't answered this part.") ?>
                                                                    </i>
                                                                    <?php $unanswered++ ?>
                                                                </div>
                                                        <?php endif; ?>
                                                <?php else: ?>
                                                        <div class="form-group q-part-ans-type" data-id="<?= $qPartData['ans_area']['type'] ?>">
                                                            <?php if ($qPartData['ans_area']['type'] == 'textbox'): ?>
                                                                    <div id="ansBkp<?= $qPart ?>" style="display:none"><?= htmlentities($answerData[$qPart]['ans'][0]) ?></div>
                                                                    <input type="text" class="form-control changeable" value="<?= htmlentities($answerData[$qPart]['ans'][0]) ?>" placeholder="<?= $tr->_("Write your answer here ...") ?>" />
                                                            <?php elseif ($qPartData['ans_area']['type'] == 'canvas'): ?>
                                                                    <?php
                                                                    $drawingJson = trim(json_encode($answerData[$qPart]['ans'][0]['canvasJson']), '"');
                                                                    $imageUrl = $qPartData['ans_area']['back'] ? $this->url->get(current($qPartData['ans_area']['back'])) : "";
                                                                    $elementId = sprintf("s%dq%dp%s", $student->id, $qObj->id, $qPart);

                                                                    ?>
                                                                    <div id="<?= $elementId ?>" class="literally changeable"></div>
                                                                    <button class="fullscreen btn btn-block" isfor="<?= $elementId ?>" style="background-color: ghostwhite">
                                                                        <?= $tr->_("Fullscreen") ?>
                                                                    </button>    
                                                                    <script language="javascript">canvasInit('<?= $elementId ?>', '<?= $drawingJson ?>', '<?= $imageUrl ?>');</script>
                                                            <?php elseif ($qPartData['ans_area']['type'] == 'choicebox'): ?>
                                                                    <?php $type = (count(array_filter($qPartData['ans_area']['data'])) == 1) ? 'radio' : 'checkbox'; ?>
                                                                    <div class="col-md-10">
                                                                        <?php $i = 0; ?>
                                                                        <?php foreach ($qPartData['ans_area']['data'] as $qPartOpt => $ans): ?>
                                                                                <div class="checkbox">
                                                                                    <div>
                                                                                        <input <?= $type == 'radio' ? 'name="' . $qObj->slot . '-' . $qPart . '"' : '' ?> type="<?= $type ?>" value="<?= htmlspecialchars($qPartOpt) ?>" class="changeable" <?= isset($answerData[$qPart]['ans']) && in_array($qPartOpt, $answerData[$qPart]['ans']) ? 'checked="checked"' : '' ?>>
                                                                                        <?= $qPartOpt ?>
                                                                                    </div>
                                                                                </div>
                                                                                <?php $i++; ?>
                                                                        <?php endforeach; ?>
                                                                    </div>                                                                        
                                                            <?php else: ?>
                                                                    <div id="ansBkp<?= $qPart ?>" style="display:none"><?= $answerData[$qPart]['ans'][0] ?></div>
                                                                    <textarea id="q-<?= $qObj->slot ?>_part-<?= $qPart ?>" class="form-control changeable ckeditor" word-count-limit="<?= $qPartData['ans_area']['word_count'] ?>" native-spell-check="<?= $qPartData['ans_area']['spell_check'] ?>" style="display: none"><?= $answerData[$qPart]['ans'][0] ?></textarea>
                                                            <?php endif; ?>
                                                        </div>
                                                <?php endif; ?>
                                            </div>
                                            <?php if (count($qPartData['resources'])): ?>
                                                    <div class="q-part-resource-area col-sm-2">
                                                        <div class="box">
                                                            <div class="lead" style="font-size:15px"> 
                                                                <i class="icon-file-text-alt text-contrast resource-file" style="cursor: pointer" title="Hide resource files"></i> 
                                                                <?= $tr->_("Supplementary material") ?> 
                                                            </div>

                                                            <?php
                                                            foreach ($qPartData['resources'] as $resTitle => $resUrl) {

                                                                    $type = basename(dirname($resUrl));
                                                                    $path = $this->config->application->mediaDir . $type . DIRECTORY_SEPARATOR . basename(urldecode($resUrl));
                                                                    $href = $this->url->get($resUrl);
                                                                    $name = $resTitle;

                                                                    // 
                                                                    // Use resource viewer:
                                                                    // 
                                                                    $this->partial('partials/resource-file-viewer', array(
                                                                            'type' => $type, 'path' => $path,
                                                                            'href' => $href, 'name' => $name,
                                                                            'url'  => $this->url
                                                                    ));
                                                            }

                                                            ?>

                                                        </div>
                                                    </div>                                            
                                            <?php endif; ?>            
                                        </fieldset>
                                        <?php if ($partCount++ != count($qParts)): ?>
                                                <hr class="q-part-seprator hr-normal" />
                                        <?php endif; ?>
                                    </div>
                            <?php endforeach; ?>

                            <div style="margin:0px 15px " class="actions">
                                <div class="row q-actions">
                                    <?php if ($viewMode == 'single'): ?>
                                            <div style="padding-bottom:25px">
                                                <div style="font-weight:normal">
                                                    <input type="checkbox" id="highlight_q" value="1" class="changeable" <?= $answerData['highlight-q'] == 'yes' ? 'checked' : '' ?> <?= $testMode ? 'disabled' : '' ?>>
                                                    <span style="font-size:14px">
                                                        <?= $tr->_("I would like to review my answer for this question later on, so mark it.") ?>
                                                    </span>
                                                </div>
                                            </div>
                                            <?php if ($prevQuestId && $prevQuestId != $qObj->id): ?>
                                                    <a class="sync-answer" href="#" hlink="<?= $this->url->get('exam/' . $exam->id . '/question/' . ($prevQuestId)) ?>">
                                                        <button class="btn btn-prev">
                                                            <i class="icon-arrow-left"></i> 
                                                            <?= $tr->_("Previous Question") ?> 
                                                        </button>
                                                    </a>
                                            <?php endif; ?>

                                            <?php if ($nextQuestId): ?>
                                                    <a class="sync-answer" href="#" hlink="<?= $this->url->get('exam/' . $exam->id . '/question/' . ($nextQuestId)) ?>">
                                                        <button class="btn btn-success btn-next"> 
                                                            <?= $tr->_("Next Question") ?> 
                                                            <i class="icon-arrow-right"></i>
                                                        </button>
                                                    </a>
                                            <?php else: ?>
                                                    <a class="sync-answer" href="#" hlink="<?= $this->url->get('exam/' . $exam->id . '/question/all') ?>">
                                                        <button class="btn btn-success btn-next">
                                                            <i class="icon-list"></i> 
                                                            <?= $tr->_("Preview your answers for all questions") ?>
                                                        </button>
                                                    </a>
                                            <?php endif; ?>
                                    <?php else: ?>
                                            <a href="<?= $this->url->get('exam/' . $exam->id . '/question/' . ($qObj->id)) ?>">
                                                <button class="btn btn-success btn-prev">
                                                    <i class="icon-pencil"></i> 
                                                    <?= $tr->_("Change your answer") ?>
                                                </button>
                                            </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>        

                </div>
            </div>
            <?php
            if ($qSize == 1) {
                    break;
            }
    endforeach;

    ?>
    <?php if ($unanswered > 0) : ?>
            <div class="alert alert-warning alert-dismissable" style="margin:15px 0px;">  
                <a href="#" data-dismiss="alert" class="close">×</a>
                <p>
                    <strong>
                        <?= $tr->_("Missed to answer some questions?") ?>
                    </strong>
                </p>
                <p>
                    <?= $tr->_("One or more questions are not yet answered.") ?> 
                    <?= $tr->_("Please go back and answer all parts if you have missed one.") ?>
                </p>
            </div>
    <?php endif; ?>
</div>

<div class="ans-sync-msg">
    <?= $tr->_("Saving ...") ?>
</div>

<div id="exam-instructions" style="max-width:800px; display:none; font-family:Verdana, Geneva, sans-serif;">
    <h2 style="color: #c2100c">
        <?= $tr->_("Exam instructions: %name%", array('name' => $exam->name)) ?>
    </h2>
    <hr>
    <div class="alert alert-info">
        <?= $exam->descr ?>
    </div>
</div>

<div id="general-instructions" style="max-width:800px; display:none; font-family:Verdana, Geneva, sans-serif;">
    <h2 style="color: #c2100c">
        <?= $tr->_("General exam instructions: %name%", array('name' => $exam->name)) ?>
    </h2>
    <hr>
    <div class="alert alert-info">
        <?= $tr->_("Use the buttons in the heading to minimize the left pane or increase the text size under exam info") ?> 
        <?= $tr->_("You may again read the instructions, access a preview of all your answers and log out when you are done.") ?> 
        <?= $tr->_("You can hover over images (in supplementary material) to zoom. You can see full size image by clicking on it.") ?>
    </div>
    <div style="padding-bottom:10px">
        <br />
        <strong>
            <?= $tr->_("Important to know:") ?>
        </strong>
        <br><br>
        <ul>
            <li>
                <?= $tr->_("All your answers are continuously saved every 10 seconds if changed or when switching between question.") ?>
            </li><br>
            <li>
                <?php $prevbtn = sprintf("<button class=\"btn btn-xs\" disabled=\"disabled\"><i class=\"icon-arrow-left\"></i> %s </button>", $tr->_("Previous Question")) ?>
                <?php $nextbtn = sprintf("<button class=\"btn btn-xs btn-success\" disabled=\"disabled\"><i class=\"icon-arrow-right\"></i> %s </button>", $tr->_("Next Question")) ?>
                <?= $tr->_("It is highly recommended that you <u>don't</u> use \"back\" and \"forward\" buttons in the browser to navigate between questions.") ?>
                <?= $tr->_("Always use the %prevbtn% and %nextbtn% buttons or question links in left hand side menu.", array('prevbtn' => $prevbtn, 'nextbtn' => $nextbtn)) ?>
            </li>
            <br>
            <li>
                <?= $tr->_("Please report to invigilator immediately if any button or link do not work.") ?>
                <?= $tr->_("In such a case, please don't close/refresh web browser otherwise we may loose your answer.") ?>
                <?= $tr->_("If you see any error message from system, it is highly important that you <u>don't</u> refresh/close the web page before you report.") ?>
            </li>
            <br>
        </ul>
    </div>
</div>

<?= Tag::javascriptInclude('js/jquery.media.js?ver=0.99'); ?>
<?= Tag::javascriptInclude('js/jquery.elevatezoom.js?ver=3.0.8'); ?>
<?= Tag::javascriptInclude('plugins/ckeditor/ckeditor.js?ver=4'); ?>
<?= Tag::javascriptInclude('plugins/ckeditor/adapters/jquery.js?ver=4'); ?>

<script language="javascript" type="text/javascript">
<?php if (!$testMode && $viewMode == 'single'): ?>
                var qName = '<?= $qObj->slot ?>';
                var ansId = '<?= $answer[$qObj->id]->id ?>';
                if (ansId === '') {
                    alert("<?= $tr->_("System will not be able to save your answer for this question. Please report this issue to exam invigilators immediately.") ?>");
                }
<?php else: ?>
                var ansId = 'None!';
<?php endif; ?>
        var count = <?= (strtotime($exam->starttime) - strtotime("now")) ?>;
        setInterval(function () {
            $('.cke_button__maximize').hide();
        }, 350);
</script> 
