<?php
/*
 * Copyright (C) 2015-2018 The OpenExam Project
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// 
// File:    index.phtml
// Created: 2015-03-13 11:46:38
// 
// Author:  Anders Lövgren (Computing Department at BMC, Uppsala University)
// 

?>

<?= Phalcon\Tag::stylesheetLink('css/signup.css?rev=1'); ?>

<style>
    h1.signup {
        padding-left: 30px;
        background: url("<?= $icon ?>") no-repeat left;
    }  
</style>

<script>
        $(document).ready(function () {

            $("#td").click(function () {
                $("#te").toggle('fast')
            });

            $("#sd").click(function () {
                $("#se").toggle('fast')
            });

        });
</script>

<div class="signup">
    <h1 class="signup">
        <?= $tr->_("Signup") ?>
    </h1>
    <p>
        <?= $tr->_("The signup service allows you as student or employee to signup yourself for using the system.") ?> 
        <?= $tr->_("You will be requested to logon to continue whenever its required.") ?>
    </p>

    <?php if (isset($teacher)) { ?>
            <h3>
                <?= $tr->_("Teacher") ?>
            </h3>
            <p>
                <?= $tr->_("By continuing, you will be granted the teacher role in the system giving you permission to create your own exam.") ?> 
                <?= $tr->_("You will also get some example exams copied to your account.") ?>
            </p>
            <a href='#' id='td'>
                <?= $tr->_("Details") ?>
            </a>
            <div class="exam-listing" style='display: none' id='te'>
                <p>
                    <?= $tr->_("These example exams will be copied and associated with your account:") ?>
                </p>
                <?php
                foreach ($texams as $exam) {
                        if (!isset($exam->descr) || strlen($exam->descr) == 0) {
                                $exam->descr = $tr->_("Description is missing");
                        }

                        ?>
                        <div class="exam-content-box">
                            <div class="exam-head"><?= $exam->name ?></div>
                            <div class="exam-body"><?= $exam->descr ?></div>
                        </div>
                <?php } ?>
            </div>
    <?php } ?>

    <?php if (isset($student)) { ?>
            <h3>
                <?= $tr->_("Student") ?>
            </h3>
            <p>
                <?= $tr->_("By continuing, you will be registered as a student in the system with access to some example exams.") ?>
            </p>
            <a href='#' id='sd'>
                <?= $tr->_("Details") ?>
            </a>
            <div class="exam-listing" style='display: none' id='se'>
                <p>
                    <?= $tr->_("These example exams will be available for you to test:") ?>
                </p>
                <?php
                foreach ($sexams as $exam) {
                        if (!isset($exam->descr) || strlen($exam->descr) == 0) {
                                $exam->descr = $tr->_("Description is missing");
                        }

                        ?>
                        <div class="exam-content-box">
                            <div class="exam-head"><?= $exam->name ?></div>
                            <div class="exam-body"><?= $exam->descr ?></div>
                            <div class="exam-status">&nbsp;</div>
                        </div>
                <?php } ?>
            </div>
    <?php } ?>

    <?php if (!isset($student) && !isset($teacher)) { ?>
            <h3>
                <?= $tr->_("Continue") ?>
            </h3>
            <p>
                <?= $tr->_("By continuing, depending on you affiliation you will either be subscribed as a employee or student in the system.") ?>
                <?= $tr->_("You can also chose to click on the 'Reload' button to review this page in authenticated mode.") ?>
            </p>
    <?php } ?>

    <hr/>
    <?php if (isset($insert)) { ?>
            <input class="btn btn-green" 
                   type="submit" 
                   name="insert" 
                   value="<?= $tr->_("Signup") ?>" 
                   onclick="window.location.assign('<?= $insert ?>')" 
                   title="<?= $tr->_("Click on this button signup as a system user.") ?>"/>
           <?php } ?>
           <?php if (isset($reload)) { ?>
            <input class="btn btn-green" 
                   type="submit" 
                   name="reload" 
                   value="<?= $tr->_("Reload") ?>" 
                   onclick="window.location.assign('<?= $reload ?>')" 
                   title="<?= $tr->_("Click on this button authenticate and reload page.") ?>"/>
           <?php } ?>

    <?php if (isset($remove)) { ?>
            <h3>
                <?= $tr->_("Unsubscribe") ?>
            </h3>
            <p>
                <?= $tr->_("Click on the button below to remove yourself as a system user.") ?>
            </p>
            <hr/>
            <input class="btn btn-red" 
                   type="submit" 
                   name="insert" 
                   value="<?= $tr->_("Remove") ?>" 
                   onclick="window.location.assign('<?= $remove ?>')" 
                   title="<?= $tr->_("Click on this button remove yourself as a system user.") ?>"/>
           <?php } ?>
</div>
